name: CI

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: Run tests with coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go test -coverprofile=coverage.txt -v ./...
          go tool cover -html=coverage.txt
      - name: Run build
        run: |
          go build -o bin/workflow-tools .

      - id: tag
        if: startsWith(github.ref, 'refs/tags/')
        env:
          ref: ${{ github.ref }}
        run: echo "::set-output name=tag::${ref##*/}"

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/workflow-tools